### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by l2eused** [carlrobert/double-switch#3]
tbh, I don't know how to use this plugin. When I downloaded, I only see the option to set which theme prefer but not the commard nor hotkey appear. Did I misunderstood about this plugin?

**Comment by carlrobert** [comment]
Hi, Have you tried switching between dark and light mode in the Obsidian
settings?

Best regards,
Robert

**Comment by carlrobert** [comment]
@l2eused Forgot to mention that there is another similar theme that switches between light and dark mode on a set time schedule: https://github.com/CyberT17/obsidian-day-and-night

I'm not the author of that theme and haven't used it extensively; your mileage may vary.
